{{- if .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "titan-v-app.fullname" . }}
  labels:
    {{- include "titan-v-app.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "titan-v-app.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.openshift.route.host }}
  host: {{ .Values.openshift.route.host }}
  {{- end }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
{{- end }}
